import {
  BookOpen,
  Bot,
  BriefcaseBusiness,
  Building2,
  Calendar,
  Circle,
  CircleDot,
  Code2,
  Cog,
  Diamond,
  Gamepad2,
  GraduationCap,
  Handshake,
  HeartHandshake,
  Hexagon,
  Lightbulb,
  Megaphone,
  Network,
  Palette,
  Rocket,
  Shield,
  Sparkles,
  Square,
  Triangle,
  Trophy,
  Users,
  UsersRound,
  Wrench,
  type LucideIcon,
} from "lucide-react"

// Persist these stable names, not glyphs. Keep this catalog in sync with the public app.
// Offer users-round explicitly; users is the old default used by public legacy styling.
export const DEPARTMENT_ICONS = [
  "users-round",
  "building2",
  "code2",
  "bot",
  "palette",
  "megaphone",
  "calendar",
  "cog",
  "wrench",
  "shield",
  "lightbulb",
  "sparkles",
  "trophy",
  "gamepad2",
  "book-open",
  "graduation-cap",
  "rocket",
  "network",
  "briefcase-business",
  "handshake",
  "heart-handshake",
] as const

export const DEPARTMENT_ICON_COMPONENTS: Record<string, LucideIcon> = {
  users: Users,
  "users-round": UsersRound,
  building2: Building2,
  code2: Code2,
  bot: Bot,
  palette: Palette,
  megaphone: Megaphone,
  calendar: Calendar,
  cog: Cog,
  wrench: Wrench,
  shield: Shield,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  trophy: Trophy,
  gamepad2: Gamepad2,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  rocket: Rocket,
  network: Network,
  "briefcase-business": BriefcaseBusiness,
  handshake: Handshake,
  "heart-handshake": HeartHandshake,
  // Previously saved symbols stay recognizable without exposing text as an icon.
  "◈": Diamond,
  "◇": Diamond,
  "⬡": Hexagon,
  "⬢": Hexagon,
  "◎": CircleDot,
  "◉": CircleDot,
  "△": Triangle,
  "□": Square,
  "○": Circle,
}
